User interface
m-anwar97/Tic-Tac-Toe pull request #2
Opened 2020-10-08 03:36 UTC by coldatlas

Added user interface and loop turns in main file

2020-10-08 06:06 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

- Great job on creating a decent README at this milestone 👏 !
- You are accepting players' names at the start. This makes your game stand out more. Good job there.

### But in order to get it approved, we need to work on some changes. Let's see...

- While running your game, after player name inputs, the game launches an infinite loop. I have left a comment below about it. Be sure to check it out.

- Great use of inline comments to show the game flow. But you also need to inform the players about their turns in the console. You can convert the comments on lines 21 and 24 to `puts` statements. But you are free to do it however you want.

- You need to display the game board after asking each player to place their tokens. You can display an empty board or tokens placed anywhere you like. You can convert the comments on lines 22 and 25 to `puts` statements. But you are free to do it however you want.

- Your game should be able to ask the player where it should place a token (position) after showing available positions. Remember, you just have to mock it. You are not required to implement a game logic.

- Your game should be able to inform a player if the selected move is invalid (without computing what an invalid move is).

- Your game should inform players if the selected move is a winning move (without computing the winning move).

- Your game should inform players if the selected move is a draw move (without computing draw).

- Remember to repeat all actions for the next player's move.

2020-10-08 06:06 UTC, tirthajyoti-ghosh commented on bin/main
> +end
This loop is running infinitely as there is no terminating condition. Please introduce a terminating condition to stop this behavior.

2020-10-08 06:06 UTC, tirthajyoti-ghosh commented on bin/main
> +  print '╔═══╦═══╦═══╗ \n ║   ║   ║   ║ \n ╠═══╬═══╬═══╣ \n ║   ║   ║   ║ \n ╠═══╬═══╬═══╣
Since you are using single-quotes (`'`), the escape characters will not work. Use double-quotes (`"`).

2020-10-08 06:07 UTC, tirthajyoti-ghosh requested changes
#### Summary

* [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
* [x] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
* [ ] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
* [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
* [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
* [x] `[REQUIRED]` game repeats all actions for the next player's move

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-14 08:10 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle:  :stop_sign: 
### HELLO :wave: YOU HAVE DONE SUCH A GREAT JOB :+1: GREAT WORK IMPROVING THE APPLICATION JUST LIKE SUGGESTED BY THE PREVIOUS TSE :+1: 

### JUST SOME FEW MORE IMPROVEMENTS TO BE MADE AND WE SHALL BE GOOD TO GO :smile: 

- [ ] The game should display the board after the players move. (without computing which spots on the board are taken).

![display board](https://user-images.githubusercontent.com/32361963/95960963-1be09980-0e0d-11eb-9577-104057f091c7.png)

- [ ] The game should be able to tell the player if it's a winning move (without computing the winning move). You don't have to write the logic of this.

- [ ]  The game informs the player if the selected move is invalid (without computing what an invalid move is)

### if you have any question concerning the review kindly reach me on slack @peterrobert


### HAPPY CODING :computer:

2020-10-23 08:09 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO :wave: VERY NICE PROGRESS BUT THERE ARE STILL SOME MORE REQUIREMENTS THAT HAVENT BEEN MET YET. KINDLY CHECK BELOW :arrow_down: 

- [ ] Your game just outputs that the game is a draw, which is okay but you need also to inform the player if the selected move is a winning move (without computing the winning move)

- [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)

### if you have any question kindly reach me on slack @peterrobert 

### HAPPY CODING :computer:

2020-10-23 17:32 UTC, krys2fa commented
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this milestone approved. 👍 

I am suggesting some optional changes to make your project even better. They are as follows:

- [ ] [OPTIONAL] The game accepts empty names. You should validate this to ensure your game can be played without any confusion.

- [ ] [OPTIONAL] The game accepts any key as the symbol to be used by the players. You should validate this as well so players can only choose `X` or `O` as the game instructions have prompted them.

You can now merge this branch into the development branch and go on with your next milestone.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-10-23 21:12 UTC, merged